import { StyleSheet } from 'react-native';

/** Layout and typography compose the notebook's existing theme surfaces and colors. */
export const templateStyles = StyleSheet.create({
  content: { flexGrow: 1, flexShrink: 0, paddingVertical: 24 },
  compactContent: { paddingHorizontal: 16, paddingVertical: 20 },
  workspace: { width: '100%', maxWidth: 1200, alignSelf: 'center', gap: 20 },
  row: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  wrap: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 },
  steps: { alignSelf: 'flex-end' },
  between: { justifyContent: 'space-between' },
  grow: { flex: 1, minWidth: 0 },
  intro: { maxWidth: 680, fontSize: 14, lineHeight: 22 },
  title: { fontSize: 18, lineHeight: 26, marginBottom: 0 },
  label: { fontSize: 13, lineHeight: 20 },
  section: { gap: 16 },
  panel: { borderRadius: 16, marginBottom: 0, padding: 20, shadowOpacity: 0, elevation: 0 },
  criteria: { minHeight: 48, maxWidth: '100%' },
  previewPanel: { paddingBottom: 0, overflow: 'hidden' },
  badge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8, overflow: 'hidden' },
  catalogGroup: { gap: 14 },
  choice: { borderRadius: 12, padding: 14, minWidth: 0, gap: 10 },
  pressed: { opacity: 0.75 },
  disabled: { opacity: 0.5 },
  choiceTitle: { fontSize: 16, lineHeight: 22, fontWeight: '600' },
  iconTile: {
    borderRadius: 10,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outline: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, paddingLeft: 52 },
  outlineText: { fontSize: 13, lineHeight: 19, maxWidth: '100%' },
  empty: { padding: 32, alignItems: 'center', gap: 16 },
  emptyText: { textAlign: 'center', maxWidth: 460, lineHeight: 22 },
  columns: { flexDirection: 'row', alignItems: 'flex-start', gap: 20 },
  stack: { gap: 20 },
  previewColumn: { flex: 1, minWidth: 0 },
  sourceColumn: { width: 280, minWidth: 0 },
  formColumn: { flex: 1, minWidth: 0 },
  editorColumn: { flex: 1.4, minWidth: 0 },
  viewerFrame: {
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: 1,
    marginTop: 16,
    marginHorizontal: -20,
  },
  noteList: { flex: 1, marginHorizontal: -20 },
  scrollContent: { paddingHorizontal: 20 },
  noteRow: { borderWidth: 0, paddingHorizontal: 10, paddingVertical: 9, marginVertical: 2, gap: 8 },
  noteText: { fontSize: 13, lineHeight: 19 },
  sourceRootRow: { minHeight: 48, paddingHorizontal: 12, paddingVertical: 12, marginVertical: 4 },
  sourceRootText: { fontSize: 14, lineHeight: 20, fontWeight: '600' },
  children: { paddingLeft: 12, borderLeftWidth: 1, marginLeft: 18 },
  folder: { padding: 0, backgroundColor: 'transparent' },
  fields: { gap: 14 },
  input: { marginBottom: 0, minHeight: 44, fontSize: 15, borderRadius: 10 },
  field: { gap: 6 },
  titleChoices: { maxHeight: 200, marginHorizontal: -20 },
  titleChoice: { marginBottom: 8 },
  helper: { lineHeight: 20, fontSize: 12 },
  formActions: { marginTop: 4 },
  divider: { marginVertical: 2 },
  editor: { minHeight: 400 },
  notice: { padding: 14, borderRadius: 10 },
});
